#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H724.UI.Web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hotels")]
	public partial class tblRoomsReservationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblRoomsReservation(tblRoomsReservation instance);
    partial void UpdatetblRoomsReservation(tblRoomsReservation instance);
    partial void DeletetblRoomsReservation(tblRoomsReservation instance);
    #endregion
		
		public tblRoomsReservationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HotelsConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public tblRoomsReservationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tblRoomsReservationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tblRoomsReservationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tblRoomsReservationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblRoomsReservation> tblRoomsReservations
		{
			get
			{
				return this.GetTable<tblRoomsReservation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRoomsReservation")]
	public partial class tblRoomsReservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CustomerSessionId;
		
		private string _ItineraryId;
		
		private string _ConfirmationNo;
		
		private string _ReservationStatus;
		
		private string _ArrivalDate;
		
		private string _DepartureDate;
		
		private string _HotelName;
		
		private string _HotelAddress;
		
		private string _HotelCity;
		
		private string _RoomDescription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCustomerSessionIdChanging(string value);
    partial void OnCustomerSessionIdChanged();
    partial void OnItineraryIdChanging(string value);
    partial void OnItineraryIdChanged();
    partial void OnConfirmationNoChanging(string value);
    partial void OnConfirmationNoChanged();
    partial void OnReservationStatusChanging(string value);
    partial void OnReservationStatusChanged();
    partial void OnArrivalDateChanging(string value);
    partial void OnArrivalDateChanged();
    partial void OnDepartureDateChanging(string value);
    partial void OnDepartureDateChanged();
    partial void OnHotelNameChanging(string value);
    partial void OnHotelNameChanged();
    partial void OnHotelAddressChanging(string value);
    partial void OnHotelAddressChanged();
    partial void OnHotelCityChanging(string value);
    partial void OnHotelCityChanged();
    partial void OnRoomDescriptionChanging(string value);
    partial void OnRoomDescriptionChanged();
    #endregion
		
		public tblRoomsReservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerSessionId", DbType="VarChar(200)")]
		public string CustomerSessionId
		{
			get
			{
				return this._CustomerSessionId;
			}
			set
			{
				if ((this._CustomerSessionId != value))
				{
					this.OnCustomerSessionIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerSessionId = value;
					this.SendPropertyChanged("CustomerSessionId");
					this.OnCustomerSessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItineraryId", DbType="VarChar(150)")]
		public string ItineraryId
		{
			get
			{
				return this._ItineraryId;
			}
			set
			{
				if ((this._ItineraryId != value))
				{
					this.OnItineraryIdChanging(value);
					this.SendPropertyChanging();
					this._ItineraryId = value;
					this.SendPropertyChanged("ItineraryId");
					this.OnItineraryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmationNo", DbType="VarChar(100)")]
		public string ConfirmationNo
		{
			get
			{
				return this._ConfirmationNo;
			}
			set
			{
				if ((this._ConfirmationNo != value))
				{
					this.OnConfirmationNoChanging(value);
					this.SendPropertyChanging();
					this._ConfirmationNo = value;
					this.SendPropertyChanged("ConfirmationNo");
					this.OnConfirmationNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationStatus", DbType="VarChar(50)")]
		public string ReservationStatus
		{
			get
			{
				return this._ReservationStatus;
			}
			set
			{
				if ((this._ReservationStatus != value))
				{
					this.OnReservationStatusChanging(value);
					this.SendPropertyChanging();
					this._ReservationStatus = value;
					this.SendPropertyChanged("ReservationStatus");
					this.OnReservationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArrivalDate", DbType="VarChar(100)")]
		public string ArrivalDate
		{
			get
			{
				return this._ArrivalDate;
			}
			set
			{
				if ((this._ArrivalDate != value))
				{
					this.OnArrivalDateChanging(value);
					this.SendPropertyChanging();
					this._ArrivalDate = value;
					this.SendPropertyChanged("ArrivalDate");
					this.OnArrivalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartureDate", DbType="VarChar(100)")]
		public string DepartureDate
		{
			get
			{
				return this._DepartureDate;
			}
			set
			{
				if ((this._DepartureDate != value))
				{
					this.OnDepartureDateChanging(value);
					this.SendPropertyChanging();
					this._DepartureDate = value;
					this.SendPropertyChanged("DepartureDate");
					this.OnDepartureDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelName", DbType="VarChar(400)")]
		public string HotelName
		{
			get
			{
				return this._HotelName;
			}
			set
			{
				if ((this._HotelName != value))
				{
					this.OnHotelNameChanging(value);
					this.SendPropertyChanging();
					this._HotelName = value;
					this.SendPropertyChanged("HotelName");
					this.OnHotelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelAddress", DbType="VarChar(300)")]
		public string HotelAddress
		{
			get
			{
				return this._HotelAddress;
			}
			set
			{
				if ((this._HotelAddress != value))
				{
					this.OnHotelAddressChanging(value);
					this.SendPropertyChanging();
					this._HotelAddress = value;
					this.SendPropertyChanged("HotelAddress");
					this.OnHotelAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelCity", DbType="VarChar(300)")]
		public string HotelCity
		{
			get
			{
				return this._HotelCity;
			}
			set
			{
				if ((this._HotelCity != value))
				{
					this.OnHotelCityChanging(value);
					this.SendPropertyChanging();
					this._HotelCity = value;
					this.SendPropertyChanged("HotelCity");
					this.OnHotelCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomDescription", DbType="VarChar(400)")]
		public string RoomDescription
		{
			get
			{
				return this._RoomDescription;
			}
			set
			{
				if ((this._RoomDescription != value))
				{
					this.OnRoomDescriptionChanging(value);
					this.SendPropertyChanging();
					this._RoomDescription = value;
					this.SendPropertyChanged("RoomDescription");
					this.OnRoomDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
